"""create runs table

Revision ID: 0ee779db8292
Revises: 
Create Date: 2026-07-31 10:26:28.539263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ee779db8292'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='run_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('continuation_mode', sa.Enum('fresh', 'resume', name='continuation_mode', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('source_run_id', sa.BigInteger(), nullable=True),
    sa.Column('source_checkpoint', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), server_default=sa.text("'Place for my notes'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('config_schema_version', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('config_sha256', sa.String(length=64), nullable=False),
    sa.Column('raw_config_yaml', sa.Text(), nullable=False),
    sa.Column('normalized_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_path', sa.Text(), nullable=False),
    sa.Column('data_sha256', sa.String(length=64), nullable=False),
    sa.Column('duration_unit', sa.Enum('data_epochs', 'timesteps', name='training_duration_unit', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('duration_amount', sa.BigInteger(), nullable=False),
    sa.Column('split_index', sa.BigInteger(), nullable=False),
    sa.Column('train_rows', sa.BigInteger(), nullable=False),
    sa.Column('validation_rows', sa.BigInteger(), nullable=False),
    sa.Column('steps_per_data_epoch', sa.BigInteger(), nullable=False),
    sa.Column('training_steps_requested', sa.BigInteger(), nullable=False),
    sa.Column('training_steps_completed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('data_epochs_completed', sa.Numeric(precision=18, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            (\n                continuation_mode = 'fresh'\n                AND source_run_id IS NULL\n                AND source_checkpoint IS NULL\n            )\n            OR\n            (\n                continuation_mode = 'resume'\n                AND source_run_id IS NOT NULL\n                AND source_checkpoint IS NOT NULL\n                AND length(trim(source_checkpoint)) > 0\n            )\n            ", name=op.f('ck_runs_continuation_fields')),
    sa.CheckConstraint('\n            source_run_id IS NULL\n            OR source_run_id <> id\n            ', name=op.f('ck_runs_source_run_not_self')),
    sa.CheckConstraint('\n            training_steps_completed >= 0\n            AND\n            training_steps_completed\n                <= training_steps_requested\n            ', name=op.f('ck_runs_completed_steps_range')),
    sa.CheckConstraint('data_epochs_completed >= 0', name=op.f('ck_runs_completed_epochs_nonnegative')),
    sa.CheckConstraint('duration_amount >= 1', name=op.f('ck_runs_duration_amount_positive')),
    sa.CheckConstraint('split_index = train_rows', name=op.f('ck_runs_split_matches_train_rows')),
    sa.CheckConstraint('steps_per_data_epoch >= 1', name=op.f('ck_runs_steps_per_epoch_positive')),
    sa.CheckConstraint('train_rows >= 1', name=op.f('ck_runs_train_rows_positive')),
    sa.CheckConstraint('training_steps_requested >= 1', name=op.f('ck_runs_requested_steps_positive')),
    sa.CheckConstraint('validation_rows >= 1', name=op.f('ck_runs_validation_rows_positive')),
    sa.ForeignKeyConstraint(['source_run_id'], ['runs.id'], name=op.f('fk_runs_source_run_id_runs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('name', name='uq_runs_name')
    )
    op.create_index(op.f('ix_runs_source_run_id'), 'runs', ['source_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_source_run_id'), table_name='runs')
    op.drop_table('runs')
    # ### end Alembic commands ###
