"""add evaluations

Revision ID: e2791a47c401
Revises: d0ac5c43a0d4
Create Date: 2026-07-31 12:58:10.828462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2791a47c401'
down_revision: Union[str, Sequence[str], None] = 'd0ac5c43a0d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('checkpoint_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='evaluation_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('trigger', sa.Enum('scheduled', 'final', 'manual', name='evaluation_trigger', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('deterministic', sa.Boolean(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('data_scope', sa.Enum('run_validation', 'extended_out_of_sample', 'custom_range', name='evaluation_data_scope', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('data_path', sa.Text(), nullable=False),
    sa.Column('data_sha256', sa.String(length=64), nullable=False),
    sa.Column('data_rows', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_start_index', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_end_index', sa.BigInteger(), nullable=False),
    sa.Column('evaluation_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluation_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lookback_rows', sa.BigInteger(), nullable=False),
    sa.Column('steps_expected', sa.BigInteger(), nullable=False),
    sa.Column('steps_completed', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('git_commit', sa.String(length=64), nullable=False),
    sa.Column('git_branch', sa.String(length=255), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("\n            (\n                status = 'pending'\n                AND started_at IS NULL\n                AND finished_at IS NULL\n                AND steps_completed = 0\n                AND error_type IS NULL\n                AND error_message IS NULL\n            )\n            OR\n            (\n                status = 'running'\n                AND started_at IS NOT NULL\n                AND finished_at IS NULL\n                AND error_type IS NULL\n                AND error_message IS NULL\n            )\n            OR\n            (\n                status = 'completed'\n                AND started_at IS NOT NULL\n                AND finished_at IS NOT NULL\n                AND steps_completed = steps_expected\n                AND error_type IS NULL\n                AND error_message IS NULL\n            )\n            OR\n            (\n                status = 'failed'\n                AND started_at IS NOT NULL\n                AND finished_at IS NOT NULL\n                AND error_type IS NOT NULL\n                AND length(trim(error_type)) > 0\n                AND error_message IS NOT NULL\n                AND length(trim(error_message)) > 0\n            )\n            OR\n            (\n                status = 'cancelled'\n                AND started_at IS NOT NULL\n                AND finished_at IS NOT NULL\n            )\n            ", name=op.f('ck_evaluations_status_fields')),
    sa.CheckConstraint("data_sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_evaluations_data_sha256_lowercase_hex')),
    sa.CheckConstraint('\n            evaluation_start_at\n                <= evaluation_end_at\n            ', name=op.f('ck_evaluations_data_time_order')),
    sa.CheckConstraint('\n            evaluation_start_index\n                < evaluation_end_index\n            ', name=op.f('ck_evaluations_range_nonempty')),
    sa.CheckConstraint('\n            finished_at IS NULL\n            OR started_at IS NULL\n            OR finished_at >= started_at\n            ', name=op.f('ck_evaluations_execution_time_order')),
    sa.CheckConstraint('\n            steps_completed >= 0\n            AND steps_completed <= steps_expected\n            ', name=op.f('ck_evaluations_steps_completed_range')),
    sa.CheckConstraint('\n            steps_expected =\n                evaluation_end_index\n                - evaluation_start_index\n            ', name=op.f('ck_evaluations_steps_match_range')),
    sa.CheckConstraint('data_rows >= 1', name=op.f('ck_evaluations_data_rows_positive')),
    sa.CheckConstraint('evaluation_end_index <= data_rows', name=op.f('ck_evaluations_end_index_within_data')),
    sa.CheckConstraint('evaluation_start_index >= 0', name=op.f('ck_evaluations_start_index_nonnegative')),
    sa.CheckConstraint('lookback_rows >= 1', name=op.f('ck_evaluations_lookback_rows_positive')),
    sa.CheckConstraint('steps_expected >= 1', name=op.f('ck_evaluations_steps_expected_positive')),
    sa.ForeignKeyConstraint(['checkpoint_id'], ['checkpoints.id'], name=op.f('fk_evaluations_checkpoint_id_checkpoints'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations'))
    )
    op.create_index(op.f('ix_evaluations_checkpoint_id'), 'evaluations', ['checkpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_checkpoint_id'), table_name='evaluations')
    op.drop_table('evaluations')
    # ### end Alembic commands ###
